name: Build-PSModule
description: Build a PowerShell module to the PowerShell Gallery
branding:
  icon: activity
  color: blue

inputs:
  Name:
    description: Name of the module to process.
    required: false
  Path:
    description: Path to the folder where the modules are located.
    required: false
    default: src
  OutputPath:
    description: Path to the folder where the built modules are outputted.
    required: false
    default: outputs

runs:
  using: composite
  steps:
    - name: Run Build-PSModule
      shell: pwsh
      env:
        Name: ${{ inputs.Name }}
        Path: ${{ inputs.Path }}
        OutputPath: ${{ inputs.OutputPath }}
      run: . "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
