name: Build-PSModule (by PSModule)
description: Build a PowerShell module to the PowerShell Gallery.
author: PSModule
branding:
  icon: package
  color: gray-dark

inputs:
  Name:
    description: Name of the module to process.
    required: false
  Path:
    description: Path to the folder where the modules are located.
    required: false
    default: src
  ModulesOutputPath:
    description: Path to the folder where the built modules are outputted.
    required: false
    default: outputs/modules
  DocsOutputPath:
    description: Path to the folder where the built docs are outputted.
    required: false
    default: outputs/docs

runs:
  using: composite
  steps:
    - name: Run Build-PSModule
      uses: PSModule/GitHub-Script@v1
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_ModulesOutputPath: ${{ inputs.ModulesOutputPath }}
        GITHUB_ACTION_INPUT_DocsOutputPath: ${{ inputs.DocsOutputPath }}
      with:
        Script: |
          # Build-PSModule
          . "${{ github.action_path }}\scripts\main.ps1" -Verbose

    - name: Upload module artifact
      uses: actions/upload-artifact@v4
      with:
        name: module
        path: ${{ inputs.ModulesOutputPath }}
        if-no-files-found: error
        retention-days: 1

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: ${{ inputs.DocsOutputPath }}
        if-no-files-found: error
        retention-days: 1
