name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  ActionTestDefault:
    name: Action-Test - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout tests -> PSModuleTest
        uses: actions/checkout@v4
        with:
          repository: PSModule/PSModuleTest
          path: tests

      - name: Delete outputs
        shell: pwsh
        run: |
          Remove-Item -Path tests/outputs -Recurse -Force

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Action-Test
        uses: ./
        with:
          Name: PSModule
          Path: tests/src
          ModulesOutputPath: tests/outputs/modules
          DocsOutputPath: tests/outputs/docs
